### ISSUE TITLE
Failure on line 275

### ISSUE THREAD

**Issue by Agent-Soap** [begleysm/ipwatch#2] opened 2019-12-19 21:38 UTC
It was working as a for loop for 24 hours (because I couldnt get cron to work reliably). I stopped it and wanted to change the email info being used and it wouldnt start again. From /opt/ipwatch or the desktop.
I tried redownloading from source but it gave the same failure. Not sure what to do. Any suggestions?

<a href="https://ibb.co/YRdzb55"><img src="https://i.ibb.co/FxYSnQQ/HELP.png" alt="HELP" border="0"></a>

**Comment by begleysm** [comment] 2019-12-20 02:41
Interesting.  It's odd that you say it has been working for 24 hours but now isn't working.

The error is basically saying that config.try_count is ' ' (ie: nothing) instead of a number like it should be.  This suggests that your example_config.txt file is messed up or is not being opened/read properly.  Does it actually exist? Is it empty?  Does the user running ipwatch.py have permissions to open it?

I had another guy email me with the same error, it turned out that his call wasn't actually pointing to example_config.txt.

In your screenshot above you'd need to have example_config.txt located at ~/Desktop/becauseMSsucks/ipwatch/.

If you go into ipwatch.py and uncomment line 149 ```#print ("file doesn't exist\r\n")``` and run it again I suspect it will print out "file doesn't exist" prior to erroring which will tell you that you aren't pointing the software to an actual example_config.txt file.

I should probably improve the error handling with this so it's more obvious what the problem is.  I think I'll add a check at the beginning that prints a message and exits the script if the config file doesn't exist or is corrupted.

Cron should be super reliable so, on a side note, you might want to get that figured out.  To use it (and I've been running this as a cronjob once per hour for months with not interruption and it has worked...  test it every once in a while by manually changing the value in the old_ip text file) I do the following:

```sudo su``` to switch to the root user

```crontab -e``` to open up the crontab file in edit mode

and then add the following line to the bottom (to run once per hour assuming your ipwatch.py is located at /usr/local/bin/ipwatch.py and your config file is at /usr/local/share/ipwatch/config.txt)
```00 * * * * /usr/local/bin/ipwatch.py /usr/local/share/ipwatch/config.txt```

**Comment by begleysm** [comment] 2020-01-27 14:25
Closing due to inability to reproduce error and lack of interaction from the OP.

**Closed by begleysm** 2020-01-27 14:25 UTC
