### ISSUE TITLE
JSON object must be str, not 'bytes

### ISSUE THREAD

**Issue by sIRwa2** [begleysm/ipwatch#6] opened 2020-06-12 06:26 UTC
Hi, not sure if this is caused on my end.
 
`two@debiantwo:~$ sudo python3 /opt/ipwatch/ipwatch.py /opt/ipwatch/config.txt
[sudo] password for two: 
Traceback (most recent call last):
  File "/opt/ipwatch/ipwatch.py", line 278, in <module>
    currip = getip(int(config.try_count), config.ip_blacklist)
  File "/opt/ipwatch/ipwatch.py", line 162, in getip
    currip = ipgetter.myip()
  File "/opt/ipwatch/ipgetter.py", line 54, in myip
    return IPgetter().get_externalip()
  File "/opt/ipwatch/ipgetter.py", line 99, in __init__
    theList["servers"] = json.loads(data)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
`
any idea?

**Comment by begleysm** [comment] 2020-06-15 16:34
Hi @sIRwa2,

I'll try to find some time to look into this.  This is coming from a part of the code written by @TheFlyingBadger so hopefully he can help too.

I don't get this error on my machine (but I think I did get an error like this at one point when I tried to install it on a Synology box).  I'm guessing that there is a brittle call to open the JSON that might get different results depending on how the file is interpreted.

**Comment by sIRwa2** [comment] 2020-06-15 18:51
Hi. tnx for your time, some more info, im SSH-ing into the debian from macos. 1 search relating to the error mentioned utf-8. i often have errors relating this. Maybe its related?

**Comment by TheFlyingBadger** [comment] 2020-06-15 23:51
Sorry guys, i've just seen this. I'll try to take a quick look at it this evening (AWST - GMT+8). It seems a bit of a weird one, I'll mod it so that we write the returned JSON out to file immediately on receipt (as received), then attempt again after the JSON-ification of it (which is where it's failing obv)

**Comment by TheFlyingBadger** [comment] 2020-06-16 00:48
@sIRwa2 , have a go at this from my forked copy (https://github.com/TheFlyingBadger/ipwatch) - I don't think it's going to actually fix your problem - but at least we'll get a copy of servers.json as downloaded by your machine.

@begleysm - I'll put proper logging into the code when i get a chance, this at least will allow us a better view into what's actually going on.

**Comment by begleysm** [comment] 2020-06-16 17:39
Thanks @TheFlyingBadger!  I really appreciate you coming back and keeping tabs on the code you wrote.

If @sIRwa2 can't produce some debug info I think I saw the same issue on a Synology NAS that I tried to "upgrade" with your code.  So I should be able to try to get that going again if necessary.

**Comment by sIRwa2** [comment] 2020-06-16 20:52
Hi Guy's thanks for jumping on this.. Running the fork from The FLying Badger gave me this:

two@debiantwo:~$ sudo python3 /opt/ipwatch/ipwatch.py /opt/ipwatch/config.txt
  File "/opt/ipwatch/ipwatch.py", line 429
    parser.add_argument('filePath', type=checkFile, metavar='filePath', help=f"full path and filename to an IPWatch configuration file")
                                                                                                                                      ^
SyntaxError: invalid syntax

**Comment by sIRwa2** [comment] 2020-09-01 20:46
any news on this?

**Comment by begleysm** [comment] 2020-09-09 15:13
Hi @sIRwa2 I'm sorry no progress has been made on this.  The truth is I'm super busy right now and I was hoping that @TheFlyingBadger would be able to jump on this since I'm not that familiar with his code.

**Comment by codevolunt** [comment] 2021-03-29 11:11
Hi all, I get exactly the same error message.

Should I try the Fork?

**Comment by begleysm** [comment] 2021-03-29 11:57
Firstly, @siRwa2, I'm sorry for letting this languish for so long.  I was unable to reproduce the error and was super busy and then... forgot about it...

@codevolunt, I am unable to reproduce that error.  However I'm hoping that I fixed it.  You can either re-clone the repo to get the update, do the following.

1. Open ipgetter.py
2. Go to line 98
3. Delete `.read()` from the end of the line

Here is the line changed in ipgetter.py here on github: https://github.com/begleysm/ipwatch/blob/814db8168ca27f1adbd79cfe0f65d676ae957dd1/ipgetter.py#L98

Let me know if this fixes the problem?

**Comment by sIRwa2** [comment] 2021-03-29 19:58
Hi, thanks for looking into this! i now get:

`Traceback (most recent call last):
  File "/opt/ipwatch/ipwatch.py", line 278, in <module>
    currip = getip(int(config.try_count), config.ip_blacklist)
  File "/opt/ipwatch/ipwatch.py", line 162, in getip
    currip = ipgetter.myip()
  File "/opt/ipwatch/ipgetter.py", line 54, in myip
    return IPgetter().get_externalip()
  File "/opt/ipwatch/ipgetter.py", line 99, in __init__
    theList["servers"] = json.loads(data)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'HTTPResponse'
`

**Comment by sIRwa2** [comment] 2021-03-29 19:59
lol, sorry didnt meant to close..

**Comment by codevolunt** [comment] 2021-03-30 17:29
Thank you from me too!

I get exactly the same error.

I'm using raspian stretch.

Cheers

**Comment by begleysm** [comment] 2021-03-30 17:39
Interesting.  Both the original and modified variants work for me.  I'm just running Ubuntu 18.04 & a standard, up-to-date version of Python 3.  Perhaps I'll need to setup a Raspain Stretch machine and see if I can reproduce your error.

@codevolunt can you expound on your setup?  What steps did you go through to install Python, get IPWatch, etc?

@sIRwa2 what is your setup?  What OS, how was Python installed, etc?

**Comment by sIRwa2** [comment] 2021-03-30 17:44
Im running a headless vanilla Debian stretch on VMware ESXI . 
`two@debiantwo:~$ python --version
Python 2.7.13
two@debiantwo:~$ python3 --version
Python 3.5.3
two@debiantwo:~$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
`

**Comment by codevolunt** [comment] 2021-03-30 17:56
Hi Sean, I meekly followed the instructions on Github to istall ipwatch 
and Python 3.

I'm running headless on the Pi3B+ with Version 9 of Raspbian via SSH on 
a non-standard port.

I'm no Admin, so could easily have screwed something up!

**Comment by begleysm** [comment] 2021-03-30 18:10
So you're both, essentially, on Debian Stretch.  That might be a clue.  For starters, I'll spin up a basic Debian Stretch VM, follow the instructions in this project, and see what happens!

**Comment by begleysm** [comment] 2021-03-30 18:27
Good news, I was able to reproduce the error under my new Debian Stretch VM.  I'm at work right now and don't have time to dig into it this second but I'll try and get it cleaned up and let you guys know.

**Comment by codevolunt** [comment] 2021-03-30 18:35
Sounds promising!

Thanks again. 

Kind regards


Nigel

**Comment by begleysm** [comment] 2021-03-31 13:58
I think I've fixed it now.  Try again with the new updated `ipgetter.py` or make this mod to line 98 of `ipgetter.py`

`                data               = operUrl.read().decode('utf-8')`

https://github.com/begleysm/ipwatch/blob/72e7d47e373d0be6a0cc2d80592022faa4443158/ipgetter.py#L98

**Comment by sIRwa2** [comment] 2021-03-31 14:20
This seems to do the trick!

I did had an error for i had no ipwatch folder for the oldip.txt file. "FileNotFoundError: [Errno 2] No such file or directory: '/home/two/ipwatch/oldip.txt'"

I also have a "ERROR: unable to send email" 

but 1st is fixed by creating the folder, second is unrelated to this issue i think :)

**Comment by begleysm** [comment] 2021-03-31 15:09
Glad we're past that point.  I think I'll close this issue and any other issues can be opened independently.

The code will create the oldip.txt file if it doesn't exist but won't create the folder structure.  This is probably something that it should do, but I don't think I'll spend the time on it right now.

Sending mail with python's "sendmail" can be tricky.  I don't think the issue is specific to `ipwatch`.  There are challenges related to your network setup (sending mail might be blocked by a network admin or similar) and you have to get past Gmail's security hoops (read more about this in the README) if you use Gmail.  I recommend playing around with that stuff, and possibly writing a small sendmail test program to get working in isolation (I should probably include that test program too... but again, not right now lol)!  Good luck and let me know how the sendmail thing goes.  Perhaps, if you find a specific issue I can include it in the README as something to try.

**Closed by begleysm** 2021-03-31 15:09 UTC

**Comment by sIRwa2** [comment] 2021-04-02 05:55
A gmail test program would be awesome, i don't seem to get gmail to work, maybe you can suggest an alternative like Disroot

`smtp_addr=disroot.org:587`

in your installer manual. that one works like a charm.

**Comment by begleysm** [comment] 2021-04-02 12:22
So it sounds like you're got it working.  Congrats!

The test program I mentioned would really just be a stripped down sendmail.  Nothing ties it, specifically, to Gmail.

As you have inferred, sendmail can use any mail service, not just Gmail.  Gmail is just what I used in my testing.  It does includes some extra "security" features though and other email services may be simpler to get working.

Push notifications would be cool but, as far as I know, the services like Boxcar and Pushover require accounts, fees, etc.  It would definitely be doable though.  Feel free to integrate it and send a pull request ;)

**Comment by codevolunt** [comment] 2021-04-04 00:05
Just got it working too. Thanks for fixing.

I used btinternet for email and it worked fine.

Kind regards

Nigel
